#!/bin/bash
test -n "$1" || { echo "ERROR: you must pass the configuration file as argument"; exit 1; }
docker run -it --rm --privileged --net=host -v "$1":/vpn.conf -v /dev/log:/dev/log -v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket aws-vpn-client-docker