version: "3.0"
services:
  vpn-client:
    image: rdvencioneck/aws-vpn-client
    container_name: aws-vpn-client
    network_mode: "host"
    restart: "no"
    volumes:
      - "./vpn.conf:/vpn.conf:rw"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/resolv.conf:/etc/resolv.conf:rw"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN